### GraphQL customers
GRAPHQL http://localhost:8080/graphql
Content-Type: application/graphql

query {
    customers {
        id
        name
    }
}

### GraphQL introspection
GRAPHQL http://localhost:8080/graphql
Content-Type: application/graphql

{
    __schema {
        types {
            name
        }
    }
}